---
- name: Ensure Docker Compose is installed
  apt:
    name: docker-compose
    state: present

# - name: copy Docker Compose files
#   copy:
#     src: files/{{ item }}
#     dest: /home/ubuntu/{{ item }}
#   loop:
#   - docker-compose.yaml


- name: Print the value of variable docker_version
  debug: 
    msg: "{{ debug}} "

- name: Print the value of group variable http_port
  debug: 
    msg: "{{ external_url}} "

- name: Print the value of host variable app_version
  debug: 
    msg: "{{ device_ID}} "

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_name: flask
    definition:
      version: '2'
      services:
        flask-app:
          image: "{{app_image}}"
          environment:
            - TUNING={{ tuning }}
            - DEBUG={{ debug }}
            - EXTERNAL_URL={{ external_url }}
            - CLIENT={{ client }}
            - INTERACTION_MODE={{ interaction_mode }}
            - DEVICE_ID={{ device_ID }}

          # deploy:
          #   replicas: 3
          restart: always
          networks:
            - my_network
          volumes:
            - secret-keys-volume:/app/secrets
          ports:
            - "8181:8181"

      volumes:
        secret-keys-volume:

      networks:
        my_network:

