---
- name: Deploy app
  hosts: all
  become: true

  roles:
    - docker

  tasks:

  - name: Creates directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Copy nginx.conf
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/app/nginx.conf"
      dest: /app
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy certificate
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/app/my-site.crt"
      dest: /app
      owner: ubuntu
      group: ubuntu
      mode: '0644'
    
  - name: Copy certificate key
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/app/my-site.key"
      dest: /app
      owner: ubuntu
      group: ubuntu
      mode: '0644'


  - name: Create Docker Compose file from Jinja template
    template:
      src: files/docker-compose.yaml.j2
      dest: /app/docker-compose.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Start Docker Compose services
    command: "docker compose up --scale flask-app={{ replicas }} -d"
    args:
      chdir: /app/