version: '2'
services:
  flask-app:
    image: adriannavarro/app:latest
    deploy:
      resources:
        limits:
          memory: 1G  # 1GB of RAM
          cpus: '0.3'  # 0.3 cores           
    restart: always
    networks:
      - my_network
    volumes:
      - secret-keys-volume:/app/secrets
    environment:
      - TUNING=${TUNING}
      - DEBUG=${DEBUG}
      - EXTERNAL_URL=${EXTERNAL_URL}
      - CLIENT=${CLIENT}
      - INTERACTION_MODE=${INTERACTION_MODE}
      - DEVICE_ID=${DEVICE_ID}
    ports:
      - "8181"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./my-site.crt:/etc/ssl/certs/my-site.crt
      - ./my-site.key:/etc/ssl/private/my-site.key
    depends_on:
      - flask-app
    ports:
      - "443:443"
    networks:
      - my_network

volumes:
  secret-keys-volume:
  app_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=5G

networks:
  my_network:
  

