version: '3'
services:
  flask-app:
    image: adriannavarro/app:latest

    restart: always
    networks:
      - my_network
    volumes:
      - secret-keys-volume:/app/secrets
    ports:
      - "8181:8181"

volumes:
  secret-keys-volume:

networks:
  my_network: